name: functions-name

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/*
    exclude:
    - README.md

variables:
- name: functionAppName
  value: 'func-name-env'
- name: azureSubscriptionENV
  value: 'Azure ENV'
- name: vmImageName
  value: 'windows-2019'
- name: workingDirectory
  value: 'src/xxx.Functions'
- name: systemName
  value: BatchAllocation

pool:
  vmImage: $(vmImageName)

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    workspace:
      clean: all

    pool:
      vmImage: $(vmImageName)

    steps:

    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '**\*.sln'
        feedsToUse: 'config'
        noCache: false
    
    - task: VSBuild@1
      inputs:
        solution: '**\*.sln'
        msbuildArgs: '/p:DeployOnBuild=true /p:SkipInvalidConfigurations=false /p:OutDir="$(System.DefaultWorkingDirectory)\publish_output"'
        platform: 'Any CPU'
        configuration: 'Release'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(systemName)-v$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(systemName)-v$(Build.BuildId).zip
